### ISSUE TITLE
How Does One Print an Individual Continuity

### ISSUE THREAD

**Issue by colindr** [calband/calchart#160]
Hey Folks, Colin Downs-Razouk here, phonez '05, stunt '07.  This may be a dumb question, and pardon me for asking and making an issue if it is, but is there a way in CalChart to print an individual marcher's continuity?  Like say I'm A0, is there a way to just bake out a script that says exactly what I'm supposed to be doing on every beat . Something like:

mark time west 50
march 10 south
march 8 north
mark time east 10
etc...

This may already exist, and if so, if you could point me to it that would be great.  If it doesn't, I'd be happy to help implement with a little guidance on where to start.

**Comment by noahsark769** [comment]
Hi Colin! Actually, last year we thought a lot about that problem and tried to address it in sort of an interesting way. We actually have a website called [calchart-viewer](http://calband.github.io/calchart-viewer) which is meant to serve as the go to thing for viewing shows in different ways (including generating an individual continuity).

The idea is that you can have calchart generate you a "viewer" file (actually just a blob of JSON) that you can give to the web app to read and display. [Here's an example of an individual continuity](http://calband.github.io/calchart-viewer/pdf.html?show=2015-guardians&dot=A8&md-orientation=west&bev-orientation=east&sd-orientation=east&layout-order=ltr&endsheet-widget=md) for dot A8 of this coming Saturday's show.

The printout could probably be prettier, and I'm not sure if @kmdurand has merged the code he wrote to do the JSON file generation into calchart master yet. I'm sure current Cal Band (I graduated last year) would love some help with this!

**Comment by noahsark769** [comment]
Oh, I should mention that the viewer is also open source [here](https://github.com/calband/calchart-viewer)

**Comment by colindr** [comment]
Cool!  I got the impression from some of the commit comments that this had
maybe been a part of the online viewer.

I guess my next two questions would be:

1) Is the band currently using the online viewer, and will they be
uploading a viewer file for the Alumni Band Day show?  We're trying to
figure out what would be helpful to make it easier for Alumni to learn
their spots.  However, now that I think about how it's charted I think
it'll still be fairly confusing unless there was a view that just printed
the continuity, and would collapse non-changing continuities across
stuntsheets.

2) Who should I talk to about picking up issues?

**Comment by noahsark769** [comment]
We used it all of last year, and the first shows are on there now: not sure about to what extent is planned in the future. @kmdurand should be able to fill you in on everything: he's the current computer coordinator, so he's managing all of this now! @rmpowell77 has also been active (for many many years) in calchart (this repo) development - if I recall correctly, I think he was one of the original authors.

@kmdurand you should give @colindr some info :)

**Comment by kmdurand** [comment]
Hey Colin! My name is Kevin Durand (tenor drums '12, stunt '14), and I'm currently serving as the Band's Computer Coordinator. With regard to the questions that you posted above:

1. Indeed, the band does currently use the online viewer. As of now, our first pregame and halftime shows are uploaded, and you can check them out if you'd like. The Alumni Band Day show will also be uploaded sometime in the next week, and the alumni will be able to use the viewer to generate PDFs describing their own personalized continuities. If there's any specific date that the alumni would like to have the show posted by, please let me know and I'll see what I can do.

2. The Band would love to get any help that you're willing to provide. The issues that we currently have posted could use a little updating, though. They've fallen into neglect since we don't get many people interested in CalChart. If you see one that you're interested in, go ahead and tag me in it and I'll make sure to fill in any details that aren't properly explained in the issue description.

**Comment by colindr** [comment]
Hey Kevin!

I don't know if there's a particular time when the alumni need it up on the
viewer, or whether they need it at all.  Most marchers won't get their
spots until game day, so having it early isn't too big of a win.

I'll let you know which item I try to pick up, and we'll see how well it
goes :)
