### ISSUE TITLE
Should we get rid of "mode"

### ISSUE THREAD

**Issue by rmpowell77** [calband/calchart#177]
setting mode is confusing and hard to get right.  Mode isn't part of the saved file anyways.

Do we need this feature anymore?  Could we just assume 1 mode?  What would this do to marching in other places?

**Comment by gmeeker** [comment]
Some history that might relevant:

The calchart printing code was written in the summer of 1993 as a command
line program called 'calprint' that loaded calchart 2 data and generated
Postscript files.  (Calchart 2 generated HPL or something specific to one
printer the band owned and it prevented upgrading the printer.)  That's why
Calchart 3 generated Postscript instead of using wxWidget's printing
system.  (I'm assuming that code hasn't been rewritten yet but I haven't
been following closely.)  Calchart 3 was finished much later.

Our first show in '93 was a 49'ers game at Candlestick Park.  NFL hash
marks are in a different location so 'calprint' had configurable hash
marks.  (Actually the show might have already been printed but this
convinced the DM use this for the rest of the shows.  But I'll try not to
let the facts get in the way of a good story.)  Later (in '95?) the college
hash marks were moved, so we now had three different field layouts used
over the years.  This is the first use of mode (if the band ever performs
at an NFL game again).

The second, more complicated case was spring show at Zellerbach Hall
('calprint' was long after the days of spring show at Harmon).  I believe I
got this working for spring show '94.  I copied the look of the stuntsheets
that had been done by hand (I assume by overlaying a graphic of the hall
and photocopying.)  I used some ancient tools ('xfig') to generate an EPS
file that could be inserted into the final Postscript, and the config file
specified how much of the "field" to draw.  My point is that doing this for
another venue with the current code would be tricky (I don't even remember
the details).

So I think mode is really only useful if you think the band will return to
Zellerbach or an NFL game (although changing the hash marks could be
kept).  If you were to rewrite the printing code, I could imagine using
Illustrator and saving an SVG file to import but that's not trivial.

**Comment by noahsark769** [comment]
I think the band playing at NFL games is still very much on the table given that they had a performance at a Raiders game this year :)

That said, it seems like the hash marks could just be configurable on a "per show" basis - I'm not familiar with how the code works right now, but it seems like an entire mode system is unneeded.

**Comment by rmpowell77** [comment]
We should keep mode, but have it per File.

**Comment by rmpowell77** [comment]
This is done in 3.6.0
