### ISSUE TITLE
copy/pasting stuntsheets doesn't work (Windows)

### ISSUE THREAD

**Issue by jacobjlilly** [calband/calchart#267]
Right now it pastes a stuntsheet with every point on the same spot in the center of the field (50 yd line, 10 off hash) and with 50160 beats. Can be worked around by inserting sheets from other show and selecting the same show. (using Calchart v3.5.1 on Windows 10)
![image](https://user-images.githubusercontent.com/17129876/42485770-f059c610-83ad-11e8-88a1-684a77b03429.png)

**Comment by kmdurand** [comment]
Thanks Jacob, for the descriptive bug report! I'll take a look at this now on macOS and see if I see the same result.

**Comment by kmdurand** [comment]
Happens on macOS as well, which will make this easier for me to tackle. Let me see what I can figure out...

**Comment by kmdurand** [comment]
This issue is related to an asymmetry in the way that stunt sheets are serialized and deserialized when copying and pasting. In the serialized blob, the first few bytes are populated with the number of dots in the sheet. The precise number of bytes used for this purpose is the size of `auto numPoints`, where `numPoints` is assigned as follows: 

```
auto numPoints = GetShow()->GetNumPoints();
```

During deserialization, the number of dots in the sheet is read as a uint16_t, which is not necessarily the same size as the `auto` type. It seems that in previous builds of CalChart, this `auto` indeed did have a size of `uint16_t`, but for some reason that size increased in 5.1 to the size of a `uint32_t`. Since this is the first field that is read from the serialized blob, the misunderstanding about its data size causes every field thereafter to be misread, and results in the generation of a completely corrupt stuntsheet.

**Comment by kmdurand** [comment]
Being addressed in https://github.com/calband/calchart/pull/268

**Comment by rmpowell77** [comment]
Addressed in #268
