### ISSUE TITLE
Build on Linux

### ISSUE THREAD

**Issue by DWW256** [calband/calchart#283]
Is it possible to build CalChart on Linux?  If so, how would I go about it?  Do you have a build script I could use?  Thanks!

**Comment by kmdurand** [comment]
Hi @DWW256! Good to see a new face around!

It's been many years since anyone has actively maintained the GNU/Linux variant of CalChart. It likely doesn't build right now, but I'm sure we could bring it back to life, with a little work. The old (and probably rotting) GNU/Linux `Makefile` and `README` instructions can still be found in the root directory of the repo:

https://github.com/calband/calchart/blob/master/Makefile
https://github.com/calband/calchart/blob/master/README-UBUNTU.txt

I'd be happy to work with you to get this running if you would like. What is you use case? (Do you have a timeline that you would like to see this running by?)

**Comment by DWW256** [comment]
Thanks for being so willing to help!  Of course I would like to see CalChart run on GNU/Linux eventually, but I have no pressing timeline; I just wanted to use it for fun mostly.
Unfortunately I'm not a serious developer (I know about a semester's worth of C++, heh), but I could test if you need maybe!

-Daniel Woodfield

________________________________

**Comment by gmeeker** [comment]
I initially developed CalChart on Linux (because I preferried it over
Windows and the Mac port of wxWindows wasn’t finished). Linux is well
supported by wxWindows and any OS specific code in CalChart can probably be
replaced by wxWindows utility functions.

Has anyone considered building CalChart with CMake? It might be be a
worthwhile project and allow Linux builds again. I haven’t tried followed
the code in years so take this with a grain of salt.

**Comment by gmeeker** [comment]
I should add that I was using the Motif port of wxWindows (the old name of
wxWidgets). Now Linux uses GTK on wxWidgets so there might be some minor
work involved.

**Comment by rmpowell77** [comment]
I tried doing cmake, but considering I’m so tied to Xcode (hey I work at apple!) it’s hard to make that leap.

I wonder if the better thing is to consider moving to a web-app?

Richard

**Comment by gmeeker** [comment]
You know that cmake generates projects for Xcode or Visual Studio, right?
Then you build and debug as you're used to doing.  Much easier than making
a web app.  I'd offer to work on this, but now's not a good time.  However,
I did use cmake on a somewhat complicated project (well, 5 years ago) so
feel free to hit me up with questions.  The easy stuff is easy, but
anything more complicated gets intimidating.  (I really wish they used an
existing language for scripting like python instead of rolling their own.)

You just create a *CMakeLists.txt* with something like this:
find_package(wxWidgets REQUIRED COMPONENTS net core base)
include(${wxWidgets_USE_FILE})
add_executable(myapp myapp.cpp)
target_link_libraries(myapp ${wxWidgets_LIBRARIES})

This is from here:
https://docs.wxwidgets.org/trunk/overview_cmake.html

**Comment by rmpowell77** [comment]
Just added CMake as part of CalChart.  This *should* allow use to build for Linux "easily".

@DWW256 , if you are familiar with CMake then I believe you should be able to just follow the usual flow and it should work.  I'm not a linux person so I'm not sure if it works.

**Comment by gmeeker** [comment]
That might be a little optimistic.  Some wxWidgets work to support the GTK
port might be required as it hasn't been used since the wxWidgets 1.0
days.  Most of CalChart's Linux history was with the old wxMotif port so
I'm really not sure what you'll run into.  I can answer questions, or maybe
contribute later this year.

**Comment by rmpowell77** [comment]
I believe this is working now with CMake!
